development:
  adapter: postgresql
  encoding: unicode
  database: fb_photos_development
  host: localhost
  pool: 5
  username: efatsi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fb_photos_test
  pool: 5
  username: efatsi
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fb_photos_production
  pool: 5
  username: efatsi
  password:
